#!/bin/bash

# TODO: Check for conflicting packages

dependencies=('VirtualGL')
missing_dependencies=()

for package in "${dependencies[@]}"; do
    if ! rpm -q "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies}]="$package"
    fi
done

for driver in "${DRIVERS[@]}"; do
    case "$driver" in
      nvidia)
        for i in xorg-x11-drv-nvidia-bumblebee
        do
            dependencies[${#dependencies[@]}]="$i"
        done
        ;;
      nouveau)
        for i in xorg-x11-drv-nouveau
        do
            dependencies[${#dependencies[@]}]="$i"
        done
        ;;
    esac
done

for package in "${dependencies[@]}"; do
    if ! rpm -q "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies}]="$package"
    fi
done

failed=false
# detect if cleanup is needed
if [ -f /etc/bumblebee ]; then
    echo
    echo "The installer detected an ancient installation of Bumblebee, possibly"
    echo "from git MrMEEE/bumblebee. Since that version has a lot of flaws,"
    echo "you will need to run the cleanup script first which can be done by running:"
    echo "    sudo -E ./cleanup"
    failed=true
fi

if [ ${#missing_dependencies} -gt 0 ]; then
    echo
    echo "Missing dependencies: ${missing_dependencies[*]}"
    echo
    echo "VirtualGL can be retrieved from sourceforge:"
    echo "    http://sourceforge.net/projects/virtualgl/files/VirtualGL/"
    echo "And installed by running:"
    echo "    sudo yum install <path to retrieved rpm>"
    echo
    echo "xorg-x11-drv-nvidia-bumblebee can be retrieved from:"
    echo "    url ..."
    echo "And installed by running:"
    echo "    sudo yum install <path to retrieved rpm> --nogpgcheck"
    echo
    echo "Update your package lists and install the dependencies by running:"
    echo "    sudo yum update"
    echo "    sudo yum install ${missing_dependencies[*]}"
    failed=true
fi

$failed && exit 4
